cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/dongik/workspace3/ns-allinone-3.20/ns-3.20/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/home/dongik/workspace3/ns-allinone-3.20/ns-3.20/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 140237457248144: cxx test.cpp -> test.cpp.1.o}\n[\'/usr/bin/g++\', \'-Wa;;\', \'-fno-strict-aliasing\', \'-fwrapv\', \'-fdebug-prefix-map=/build/python2.7-ZZaKJ6/python2.7-2.7.13=.\', \'-fstack-protector-strong\', \'-fno-strict-aliasing\', \'-fno-strict-aliasing\', \'-fdebug-prefix-map=/build/python2.7-ZZaKJ6/python2.7-2.7.13=.\', \'-fstack-protector-strong\', \'-fwrapv\', \'-I/usr/include/python2.7\', \'-I/usr/include/x86_64-linux-gnu/python2.7\', \'-DNS3_ASSERT_ENABLE\', \'-DNS3_LOG_ENABLE\', \'-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DHAVE_PYEMBED=1\', \'-DNDEBUG\', \'-D_FORTIFY_SOURCE=2\', \'-D_FORTIFY_SOURCE=2\', \'-DNDEBUG\', \'../test.cpp\', \'-c\', \'-o\', \'test.cpp.1.o\']\n'
